<a href="https://colab.research.google.com/github/amir-asari/SEBB4083-AI--202220232/blob/main/SEBB4083_ANN_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
def backprop(W2, W3, B2, B3, X, Y):
    alpha = 0.1   # learning rate
    N = len(X)    # number of training samples

    for i in range(N):
        x = X[i, :].reshape(-1, 1)
        y = Y[i, :].reshape(-1, 1)

        net2 = np.dot(W2.T, x) + B2
        o2 = sigmoid(net2)

        net3 = np.dot(W3.T, o2) + B3
        yh = sigmoid(net3)

        e = y - yh
        delta3 = e * yh * (1 - yh)

        delta2 = np.dot(W3, delta3) * o2 * (1 - o2)

        dW2 = alpha * np.dot(x, delta2.T)
        dW3 = alpha * np.dot(o2, delta3.T)

        dB2 = alpha * delta2
        dB3 = alpha * delta3

        W2 = W2 + dW2
        W3 = W3 + dW3

        B2 = B2 + dB2
        B3 = B3 + dB3

    return W2, W3, B2, B3

In [ ]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0, 1], [1, 0], [1, 0], [0, 1]])

W2 = np.random.rand(2, 2)
W3 = np.random.rand(2, 2)

B2 = np.random.rand(2, 1)
B3 = np.random.rand(2, 1)

# Training -------------------
for epoch in range(10000):
    W2, W3, B2, B3 = backprop(W2, W3, B2, B3, X, Y)


# Testing --------------------
N = 4
for k in range(N):
    x = X[k, :].reshape(-1, 1)
    net2 = np.dot(W2.T, x) + B2
    o2 = sigmoid(net2)

    net3 = np.dot(W3.T, o2) + B3
    yh = sigmoid(net3)

    # print(yh.T)
    print(yh)



NameError: ignored

This is example for Lecture #07-4

In [ ]:
X = np.array([[0, 1, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
Y = np.array([[0], [1], [1], [0]])

W2 = np.random.rand(3, 4)
W3 = np.random.rand(4, 1)

B2 = np.random.rand(4, 1)
B3 = np.random.rand(1, 1)

for epoch in range(10000):
    W2, W3, B2, B3 = backprop(W2, W3, B2, B3, X, Y)

N = 4
for k in range(N):
    x = X[k, :].reshape(-1, 1)
    net2 = np.dot(W2.T, x) + B2
    o2 = sigmoid(net2)

    net3 = np.dot(W3.T, o2) + B3
    yh = sigmoid(net3)

    # print(yh.T)
    print(yh)

print(W2)
print(W3)

[[0.01334657]]
[[0.97552509]]
[[0.97931528]]
[[0.02870149]]
[[ 0.64944677 -3.31209096  1.92153681  1.28570849]
 [ 0.57670903 -3.02678493  2.01920493  1.88333175]
 [ 0.53951267  4.0406194  -2.04757558 -1.59825707]]
[[ 0.04195328]
 [ 6.93626016]
 [-3.64612541]
 [-2.88561384]]
